### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by shyyx2** [daodaofr/group_reid#3]
您好 运行时遇到错误，请问应该修改哪个地方呢
......
image 1723, time : 118.384021
Computing CMC and mAP
(1724, 6720) (1724,) (6720,) (1724,) (6720,)
(1724, 6720)
(1724, 6720)
Group Reid Results ----------
mAP: 64.3%
CMC curve
Rank-1  : 66.1%
Rank-5  : 77.7%
Rank-10 : 82.1%
Rank-20 : 85.8%
------------------
(8620, 33600) (8620,) (33600,) (8620,) (33600,)
Traceback (most recent call last):
  File "main_group_gcn_siamese_part_half_fulltest_sink.py", line 687, in <module>
    main()
  File "main_group_gcn_siamese_part_half_fulltest_sink.py", line 232, in main
    rank1 = test_gcn_person_batch(model, queryloader, querygalleryloader, galleryloader, args.pool, use_gpu)
  File "main_group_gcn_siamese_part_half_fulltest_sink.py", line 676, in test_gcn_person_batch
    cmc_p, mAP_p = evaluate_person(distmat_p, q_pids_p, g_pids_p, q_camids_p, g_camids_p)
  File "/share/home/shyyx2/Greid/code/group_reid/eval_metrics.py", line 90, in evaluate_person
    remove = (g_pids[order] == q_pid) & (g_camids[order] == q_camid)
TypeError: eq() received an invalid combination of arguments - got (numpy.ndarray), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!)
 * (Number other)
      didn't match because some of the arguments have invalid types: (!numpy.ndarray!)

**Comment by handsome-rich** [comment]
您好，我运行出来准确率这些都非常低，没有找到原因。我感觉您的这个结果还是很好的，可以交流分享一下吗？
